import almondoil from '../Oil-images/almondoilimage.webp'
import avacadooil from '../Oil-images/avacadooilimage.jpg'
import  blackseedoil from '../Oil-images/blackseedoilimage.jpg'
import  castoroil from '../Oil-images/castoroilimage.jpg'
import  chiaseedoil from '../Oil-images/chiaseedoilimage.jpg'
import  coconutoil from '../Oil-images/coconutoilimage.jpg'
import  groundnutoil from '../Oil-images/groundnutoilimage.jpg'
import  oliveoil from '../Oil-images/oliveoilimage.jpg'
import  pomogranateoil from '../Oil-images/pomogranateoilimage.jpg'
import  roseoil from '../Oil-images/roseoilimage.jpg'
import  sesameoil from '../Oil-images/sesameoilimage.jpg'
import  sunflower from '../Oil-images/sunfloweroilimage.jpg'
import avacado from'../Fruit-images/Avacado.jpg'
import blueberry  from '../Fruit-images/BlueBerry.jpg'
import banana  from '../Fruit-images/banana.png'
import cherry from '../Fruit-images/Cherries.jpg'
import custard  from '../Fruit-images/custard apple.jpg'
import dragon  from '../Fruit-images/dragon fruit.jpg'
import grapes  from '../Fruit-images/Grapes.jpg'
import  greenapple from '../Fruit-images/Green apple.jpg'
import   madrin from '../Fruit-images/madrin orange.jpg'
import  mango from '../Fruit-images/Mango.jpg'
import  mathulai from '../Fruit-images/Mathulai.jpg'
import  plum from '../Fruit-images/Plums.jpg'
import arharldal from '../Pulses-images/arhardal.jpg'
import bambara from '../Pulses-images/bambara.webp'
import fenugreek from '../Pulses-images/fenugreek.jpg'
import greengram from '../Pulses-images/green gram.jpg'
import gungpeas from'../Pulses-images/gungupeas.webp'
import kaladal from'../Pulses-images/kaladal.jpg'
import rajma from '../Pulses-images/rajma.jpg'
import soya from '../Pulses-images/soya.jpg'
import beans from '../Vegetables-images/beans.jpg'
import beetroot from '../Vegetables-images/beetroot.jpg'
import brocoli from '../Vegetables-images/broccoli.jpg'
import cabbage  from '../Vegetables-images/cabbage.jpg'
import garlic from '../Vegetables-images/garlic.jpg'
import peas from '../Vegetables-images/Peas.jpg'
import mushroom from '../Vegetables-images/mushrooms.jpg'
import onion from '../Vegetables-images/Onion.jpg'
import tomato from '../Vegetables-images/tomatoes.webp'
import Corn from '../Vegetables-images/Corn.jpg'
import arharldal2 from '../Pulses-images/arhardal.jpg'
import marrowfat from '../Pulses-images/Marrowfat.jpg'
import pinto from '../Pulses-images/pintobeans.jpg'
import carrot from '../Fruit-images/carrot.jpg'
import aryan from '../Dairy-images/aryan.webp'
import butter from '../Dairy-images/butter.jpg'
import cheese from '../Dairy-images/cheese.jpg'
import clottedcream from '../Dairy-images/Clotted-Cream.jpg'
import condensemilk from '../Dairy-images/condensedmilk.webp'
import driedmilk from '../Dairy-images/driedmilk.jpg'
import ghee from '../Dairy-images/ghee.webp'
import icecreams from '../Dairy-images/ice creams.jpg'
import kerif from '../Dairy-images/kefir.jpg'
import milk from '../Dairy-images/milk.webp'
import mountain from '../images/Mountain.jpg'
import Tractor from '../images/tractor-5091577_1280.jpg'
import gif from '../Oil-images/giphy.gif'
import dash1 from '../Oil-images/dashboard1.jpg'
import dash2 from '../Oil-images/dashboard2.jpg'
import dash3 from '../Oil-images/dashboard3.jpg'
import dash4 from '../Oil-images/dashboard4.jpg'
import videoBack from '../Vegetables-images/Backgroundvideo.mp4.mp4'
import videoplayback from '../Vegetables-images/videoplayback.mp4'
import gpay from '../images/gpay.jpg'
import phonepe from '../images/phonepe.jpg'
import master from '../images/master.jpg'
import visa from '../images/visa.jpg'
import upi from '../images/upi.jpg'
import hdlogo from '../Vegetables-images/headerlogo.jpg'


const staticData={almondoil,avacadooil,blackseedoil,castoroil,chiaseedoil,coconutoil,groundnutoil,oliveoil,pomogranateoil,roseoil,sesameoil,sunflower,banana,avacado,blueberry,cherry,custard,dragon,grapes,greenapple,madrin,mango,mathulai,plum,arharldal,bambara,fenugreek,greengram,gungpeas,kaladal,rajma,soya,beans,beetroot,brocoli,cabbage,garlic,peas,mushroom,onion,tomato,Corn,arharldal2,marrowfat,pinto,carrot,aryan,milk,butter,cheese,clottedcream,condensemilk,driedmilk,ghee,icecreams,kerif,mountain,Tractor,gif,dash1,dash2,dash3,dash4,videoBack,gpay,phonepe,master,visa,upi,videoplayback,hdlogo}

export default staticData
