import Tiger from '../images/tiger-jpg.jpg'
import Building from '../images/jpg_44-2.jpg'
import Panda from '../images/Panda.jpg'
import nature from '../images/Nature.jpg'
import mountain from '../images/Mountain.jpg'
import nature2 from '../images/Nature2.jpg'
import redflower from '../images/Red flower.jpg'
import color from '../images/color.jpg'
import Organic from '../images/photo-1625246333195-78d9c38ad449.avif'
import Organic2 from '../images/Organic2.jpg'
import Organic3 from '../images/Organic3.jpg'
import Organic4 from '../images/tractor-5091577_1280.jpg'
import Organic5 from '../images/Organi55.jpg'
import sampleVideo from '../images/Video.mp4'
import almondoil from '../Oil-images/almondoilimage.webp'
import avacadooil from '../Oil-images/avacadooilimage.jpg'
import  blackseedoil from '../Oil-images/blackseedoilimage.jpg'
import  castoroil from '../Oil-images/castoroilimage.jpg'
import  chiaseedoil from '../Oil-images/chiaseedoilimage.jpg'
import  coconutoil from '../Oil-images/coconutoilimage.jpg'
import  groundnutoil from '../Oil-images/groundnutoilimage.jpg'
import  oliveoil from '../Oil-images/oliveoilimage.jpg'
import  pomogranateoil from '../Oil-images/pomogranateoilimage.jpg'
import  roseoil from '../Oil-images/roseoilimage.jpg'
import  sesameoil from '../Oil-images/sesameoilimage.jpg'
import  sunflower from '../Oil-images/sunfloweroilimage.jpg'
import avacado from'../Fruit-images/Avacado.jpg'
import blueberry  from '../Fruit-images/BlueBerry.jpg'
import banana  from '../Fruit-images/banana.png'
import cherry from '../Fruit-images/Cherries.jpg'
import custard  from '../Fruit-images/custard apple.jpg'
import dragon  from '../Fruit-images/dragon fruit.jpg'
import grapes  from '../Fruit-images/Grapes.jpg'
import  greenapple from '../Fruit-images/Green apple.jpg'
import   madrin from '../Fruit-images/madrin orange.jpg'
import  mango from '../Fruit-images/Mango.jpg'
import  mathulai from '../Fruit-images/Mathulai.jpg'
import  plum from '../Fruit-images/Plums.jpg'


const staticData = {
    Tiger,Building,Panda,nature,mountain,nature2,redflower,sampleVideo,color,Organic,Organic2,Organic3,Organic4,Organic5,almondoil,avacadooil,blackseedoil,castoroil,chiaseedoil,coconutoil,groundnutoil,oliveoil,pomogranateoil,roseoil,sesameoil,sunflower,banana,avacado,blueberry,cherry,custard,dragon,grapes,greenapple,madrin,mango,mathulai,plum
}
export default staticData;